### ISSUE TITLE
Panic in go-libp2p-kad-dht

### ISSUE THREAD

**Issue by victorb** [open-services/bolivar#5]
```
panic: assignment to entry in nil map

goroutine 287133 [running]:
github.com/jbenet/goprocess.(*process).AddChildNoWait(0xc0114b7320, 0x106ae20, 0xc011536540)
	/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:72 +0x18d
github.com/jbenet/goprocess/context.WithProcessClosing(0x105ec40, 0xc011bf3c40, 0x106ae20, 0xc0114b7320, 0xc00e330fb8, 0xc0094a0f88)
	/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/context.go:85 +0x170
github.com/jbenet/goprocess/context.OnClosingContext(...)
	/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/derive.go:12
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).queryPeer(0xc003c373b0, 0x106ae20, 0xc0114b7320, 0xc00ac396b0, 0x22)
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:270 +0x67
github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).spawnWorkers.func1(0x106ae20, 0xc0114b7320)
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.0.10/query.go:226 +0x50
github.com/jbenet/goprocess.(*process).Go.func1(0xc00c5511c0, 0xc0114b7320, 0xc0114b7380)
	/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:112 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:111 +0x1f7
```

Happens when fetching packages via ipfslite.

Seems the same as https://github.com/libp2p/go-libp2p-kad-dht/issues/334 but hasn't been released yet.

**Comment by victorb** [comment]
Fixed in https://github.com/open-services/bolivar/pull/6/commits/1acb2629f55ae5d1fa2ffa4abb1558871ffd4545
